export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_POSTS = "FETCH_POSTS";
export const ORDER_BY_VOTESCORE = "FETCH_BY_VOTESCORE";
export const ORDER_BY_TIMESTAMP = "ORDER_BY_TIMESTAMP";
