export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_POSTS = "FETCH_POSTS";
export const ADD_POST = "ADD_POST";
export const EDIT_POST = "EDIT_POST";
export const FETCH_POST_DETAILS = "FETCH_POST_DETAILS";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
